write_files:
- path: /etc/app/key
permissions: '0600'
content: | -----BEGIN RSA PRIVATE KEY-----
MIIJKAIBAAKCAgEA5F9LnTiP4RRZz8aStcaEsJDW0hkyACOSASaRFhUWx1NpSK1E
ML+2Qf4lSc0x0cOd2E27asz4FfDWXrDAyofCkcbyi94m0NjDSqO3Vh6tS++QfaQp
rJPrTsON5ZWQ4qswtU07daJxRkPg4yTgXqDLzRxchFtbpAM/4w+wX2+RRpMZ9OyQ
xnPPLD7aiPtsLg1T3TU5z8aYDV7E9r2GZest+Th3TXB1z3DJiS9dID4Km+okrEnc
BjAncoPPF8W8mYI7M3Ox7QTk+7xLtxxckwHSr91uBYhe/iuAn6Q+rKDC1qZzAhLQ
8N877yL/un0vCcDbyFEhjxbTXsBAX2Y5YOod5fsGKOAbsnYwbjhHu74xHOja3d7m
02BGY9pR2mkgm9wCMW/02tB2M8P+c1Cp23B+k0evPdOc2KVkR9dZ7iwuwM2CIfVf
xa1mPoNoI6cAPlW4h0gCWnHuY+xnJHaUKmd1syEaYqFomgk/iUhsfGXsC0od95S3
SjMfxvpOq/yaPbZeq83UA2nof56PO7gBVUsCgSJDQYVdb5EdhnDKK2J1bZtvUPDl
RZcENKpRibfTmc50ydYeCu1c3kefGXFvCotazpGCyPIKMGgDQUGQmlIhtbLqGqYD
axVcZc3qb/a0+zeKi60+Q/EWcoRwLQqv7iECi+UGlLfgTf7V25b5G1me0NECAwEA
AQKCAgBO7GQcZKTMu5TCSrT/HylSP+wN1elCxQg7X5G6mPUzU69KD59GXarmKafH
VqPGA520WEDSCx4drwrW1Kz8EWj7qk6+abruaEstq2C74YQwfw1nbml8m+4xXUHX
uxXEUDdYIOXQpKATEXhR57em3FkyfH+4uj30c68LkKt6f/sr8cCBtZPfEbziZKJv
vrxHOhHmm/NrzA1WaY8WWq9s35cWzx3j5F7Cnw73WygK8YYHFicwZ6IjfVbUq5rR
c2PXhXtiL7So3g0oto1QLfwMTg/6+UKBpPx3SJ9+DGwgirprJkEO0WPmKq/y2Bya
3ZJ5A26xTuCTK+dGkphsn85qoN5Nql3qE5JTOgrGTQ3TXR8GD3EAZmMmgxIjQCCQ
rDKmQH6k/X4pHQn8/R3K4tzegPZ3lC6cZaalPEELYPDYxafjoiSltut4uCGlyeix
J30x9M7IyuQpQjp4eXXP4bCKEDfplHXcQuX6VQzQ+YE8ZbWyPaYLI2dB7SwOqrH+
V20xpIBGZ0I5K6sd37DyymSWPVL4Jg+yvIbBVqByBgxym0YJUR4I6yYyGtwDcS8J
Q+HmcuTK1BmApfPSBtTapSQ14RoAk+DTH+RpmfNG4DPFmshJkRkeg5WPA8gzLOO2
huQm7H7tb+H7YWq23O8AFi+NzDf2fVmbXs9cm4+LfqC6vy6tRQKCAQEA/cxjjfCa
TTh1g8CmjE+LsZQPtreJIStQElXHPy4EqCRGdWb/OaymML0bNkhA6gTUnsdKDX0C
wmkoN40H05ijavny9scGUsrR/HH4Q1VJONBWo0u2X5giu1R1yknRPtnZrRHXBIiH
J9mcz4oc2LajBo7KDMQg8CE2YWlFrMihF2mKRYDcEEzjzs7qjwv7SBawtklPnG26
pBI6xSzkK+Sm4feJnG6yVcSfUta1Cwwg+EEOGozIk7OanTOFT3GCirFOLvbYYgue
fpdJwXE5+aL7eQtpBvtEauOV5bnxAu07ehvTVoi/SR6rBuG+AuTg6eyl+gBlMP5A
jLWrVyG3DbD4BwKCAQEA5lpxSh25rLoSotNrBMFlpjEGvw+wLH5qQcO1nLmnF8e/
U0Tj+TkuMEoPBbA4/oY3kjgMrr/aMbbHZMvrcB929dE2oP66ADal3ziBcqEBgDqP
GCaYPo6aZSo48oWlbvsocfilMaz1lTzCGAnVNzcDSnwZ1hgELAQGpdd/I7s4TLId
9Gs/J7xwAOjgtvEG2HFATD1NJ+kkKkB9ubcQZahWEQQxykW1tKCXzbP5KWRgIX/c
l22ft/TKbFLDabhp41f6JDTZwaF8GrcWiGxC09Vza4+lQljV+1SkrBq14K6UVzjI
g+1lmjvXopBPTQ/DJlCQSJa1QicnZfCANE9Sqj9KZwKCAQAbJplj3uBy8F5J+PsY
OY5FMgS4VEwcO0j2nSySira+0hqjhqA5KEojHqfhl7syDdA9KC644K3B5IQD5Vd4
AHVDBXhDhCkeBEqQihS4B1Cs/kS2dWwOL/VPOwra2CjFY4LQ6/6non9q+PG4lhrd
6DPqiK3+zaCEb9kkdKGaiWAKZCUBqHZiXAdm4WXgZbS9EohXB+K3Zlm4Iacd3t6N
/4kG1XdoP8NeP4mX0BZQFz0Tscnzdyoh+u3IcXGKfScs9SjbB1dAreOHwWGHizhb
h18FpP3YXFsGYFBx4gFxgbWCK6XhNQHZrak4NEAiiR+yhrl+1Dn/EsQPCYRJ7vZp
RYxTAoIBAE1MfEfKwcvchPRuzbLC00F5ojHrKctEgJOhAQiepBuuw91FeNrg/Ubn
EzNtdzKyB2Phux/I8YdNNov0ggUWCe1jT1mnIPOBYxgM9iNpM/+7ptkL2nrjj5vz
FzkK8ADV9zSHo6ePyrlRsjAu3IWyyD/udR0K4huDHlf4gImVAcd63eJvOroy2cL0
YrQBHbL0DgeHaqTB74jeK1Juw+nZG0iKh8rAqcD7QvWcNzhUno2fQn7uInKwilzf
SQPpBl9r3lzX/1qiveqZFc6hxasgLaMiiOpCtUupk7jNHctPyieavm7G8xlWi33Z
v0K0z1/EGSbCrACO8wGaOutS0wKeSnECggEBAOCHjZ5F8P7pKg1qPD9bBkoPpUwT
FdrbUNRxIUfiDC8x1hWaKAY8Keo0uFAW+mVAcrRLE3NGp7KWE/9trhU0rxHjayZ+
97rwDlCavxUCDjuXpO8CLF8WKo1micquTbsbkBL22S1rJfJEBFi5OohPHyxzVDXO
eh66H/2t4gSAS7C/3LFDuwMTGA+F10TcYe6yoQiVhrwtyznaGw03HttE1Su4nLmX
ZBhYfYXOVIqO2/i679DLhOyovLWz2P1zOdPMkgo61GWaudAlLkBMWMvbDBKkjCg7
rlGW6mGPwEbXMISAwgCcAawfMA1LRhfc58oS1n9i2A9cPKEb9xLIgtyiuTY=
-----END RSA PRIVATE KEY-----

- path: /etc/app/key.pub
permissions: '0644'
content: | -----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5F9LnTiP4RRZz8aStcaE
sJDW0hkyACOSASaRFhUWx1NpSK1EML+2Qf4lSc0x0cOd2E27asz4FfDWXrDAyofC
kcbyi94m0NjDSqO3Vh6tS++QfaQprJPrTsON5ZWQ4qswtU07daJxRkPg4yTgXqDL
zRxchFtbpAM/4w+wX2+RRpMZ9OyQxnPPLD7aiPtsLg1T3TU5z8aYDV7E9r2GZest
+Th3TXB1z3DJiS9dID4Km+okrEncBjAncoPPF8W8mYI7M3Ox7QTk+7xLtxxckwHS
r91uBYhe/iuAn6Q+rKDC1qZzAhLQ8N877yL/un0vCcDbyFEhjxbTXsBAX2Y5YOod
5fsGKOAbsnYwbjhHu74xHOja3d7m02BGY9pR2mkgm9wCMW/02tB2M8P+c1Cp23B+
k0evPdOc2KVkR9dZ7iwuwM2CIfVfxa1mPoNoI6cAPlW4h0gCWnHuY+xnJHaUKmd1
syEaYqFomgk/iUhsfGXsC0od95S3SjMfxvpOq/yaPbZeq83UA2nof56PO7gBVUsC
gSJDQYVdb5EdhnDKK2J1bZtvUPDlRZcENKpRibfTmc50ydYeCu1c3kefGXFvCota
zpGCyPIKMGgDQUGQmlIhtbLqGqYDaxVcZc3qb/a0+zeKi60+Q/EWcoRwLQqv7iEC
i+UGlLfgTf7V25b5G1me0NECAwEAAQ==
-----END PUBLIC KEY-----

